[
    [
        "31085.1",
        "568",
        "widgetAspect",
        "Landscape"
    ],
    [
        "31085.1",
        "19017",
        "widgetAspect",
        "Landscape"
    ],
    [
        "31085.1",
        "19173",
        "widgetAspect",
        "Square"
    ],
    [
        "31085.1",
        "19173",
        "widgetTarget",
        "tvguide"
    ],
    [
        "tvshows.1",
        "trending",
        "widgetTarget",
        "videos"
    ],
    [
        "tvshows.1",
        "trending",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "tvshows.1",
        "popular",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "tvshows.1",
        "airingtoday",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "tvshows.1",
        "recentlywatched",
        "widgetTarget",
        "videos"
    ],
    [
        "tvshows.1",
        "recentlywatched",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "tvshows.1",
        "inprogress",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "tvshows.1",
        "recommended",
        "widgetTarget",
        "videos"
    ],
    [
        "tvshows.1",
        "recommended",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "movies.1",
        "trending",
        "widgetTarget",
        "videos"
    ],
    [
        "movies.1",
        "trending",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "movies.1",
        "popular",
        "widgetTarget",
        "videos"
    ],
    [
        "movies.1",
        "popular",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "movies.1",
        "intheaters",
        "widgetTarget",
        "videos"
    ],
    [
        "movies.1",
        "intheaters",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "movies.1",
        "anticipated",
        "widgetTarget",
        "videos"
    ],
    [
        "movies.1",
        "anticipated",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "movies.1",
        "recommended",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "apps",
        "plugin.video.umbrella",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "apps",
        "plugin.video.thecrew",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "apps.1",
        "plugin.video.umbrella",
        "widgetTarget",
        "videos"
    ],
    [
        "apps.1",
        "plugin.video.umbrella",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "apps.1",
        "plugin.video.pov",
        "widgetTarget",
        "videos"
    ],
    [
        "apps.1",
        "plugin.video.pov",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "apps.1",
        "plugin.video.thecrew",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "apps.1",
        "plugin.video.seren",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "mylibrary.1",
        "traktwatchlist",
        "widgetTarget",
        "videos"
    ],
    [
        "mylibrary.1",
        "traktwatchlist",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "mylibrary.1",
        "continuewatching",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "searchmenu",
        "movies",
        "icon",
        "special://skin/extras/icons/film.png"
    ],
    [
        "searchmenu",
        "tvshows",
        "icon",
        "special://skin/extras/icons/tv.png"
    ],
    [
        "searchmenu",
        "20360",
        "widgetAspect",
        "Landscape"
    ],
    [
        "searchmenu",
        "20360",
        "icon",
        "special://skin/extras/icons/tv.png"
    ],
    [
        "searchmenu",
        "132",
        "widgetAspect",
        "Square"
    ],
    [
        "searchmenu",
        "132",
        "icon",
        "special://skin/extras/icons/songs.png"
    ],
    [
        "searchmenu",
        "133",
        "widgetAspect",
        "Square"
    ],
    [
        "searchmenu",
        "133",
        "icon",
        "special://skin/extras/icons/songs.png"
    ],
    [
        "searchmenu",
        "134",
        "widgetAspect",
        "Square"
    ],
    [
        "searchmenu",
        "134",
        "icon",
        "special://skin/extras/icons/songs.png"
    ],
    [
        "searchmenu",
        "musicvideos",
        "icon",
        "special://skin/extras/icons/musicvideo.png"
    ],
    [
        "searchmenu",
        "musicvideos--0",
        "icon",
        "special://skin/extras/icons/musicvideo.png"
    ],
    [
        "searchmenu",
        "31168",
        "icon",
        "special://skin/extras/icons/film.png"
    ],
    [
        "searchmenu",
        "31169",
        "icon",
        "special://skin/extras/icons/tv.png"
    ],
    [
        "searchmenu",
        "31170",
        "icon",
        "special://skin/extras/icons/sets.png"
    ],
    [
        "searchmenu",
        "31171",
        "icon",
        "special://skin/extras/icons/person.png"
    ],
    [
        "movies",
        "searchmovies",
        "icon",
        "DefaultAddonVideo.png"
    ],
    [
        "movies",
        "searchmovies",
        "thumb",
        "special://skin/extras/icons/search2.png"
    ],
    [
        "mainmenu",
        "movies",
        "widgetPath.SubmenuBumper",
        "Submenu"
    ],
    [
        "mainmenu",
        "movies",
        "widgetPath",
        "special://skin/extras/playlists/RandomMovies.xsp"
    ],
    [
        "mainmenu",
        "movies",
        "widgetTarget",
        "videos"
    ],
    [
        "mainmenu",
        "movies",
        "icon",
        "special://skin/extras/icons/film.png"
    ],
    [
        "mainmenu",
        "tvshows",
        "widgetPath.SubmenuBumper",
        "Submenu"
    ],
    [
        "mainmenu",
        "tvshows",
        "widgetPath",
        "special://skin/extras/playlists/RandomTvShows.xsp"
    ],
    [
        "mainmenu",
        "tvshows",
        "widgetTarget",
        "videos"
    ],
    [
        "mainmenu",
        "tvshows",
        "icon",
        "special://skin/extras/icons/tv.png"
    ],
    [
        "mainmenu",
        "tvshows",
        "thumb",
        "special://skin/extras/icons/"
    ],
    [
        "mainmenu",
        "mylibrary",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "mainmenu",
        "mylibrary",
        "thumb",
        "special://skin/extras/icons/book-open.png"
    ],
    [
        "mainmenu",
        "apps",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "mainmenu",
        "apps",
        "thumb",
        "special://skin/extras/icons/dice-d20.png"
    ],
    [
        "mainmenu",
        "search",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "mainmenu",
        "search",
        "thumb",
        "special://skin/extras/icons/search2.png"
    ],
    [
        "mainmenu",
        "31085",
        "widgetPath.SubmenuBumper",
        "Submenu"
    ],
    [
        "mainmenu",
        "31085",
        "icon",
        "special://skin/extras/icons/livetv.png"
    ]
]